"""Patient table additional attributes

Revision ID: 3e59077034a7
Revises: d1cd6f3b83dc
Create Date: 2026-10-09 19:25:11.114026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e59077034a7'
down_revision: Union[str, None] = 'd1cd6f3b83dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('allergies', sa.String(), nullable=False))
    op.add_column('patients', sa.Column('medical_conditions', sa.String(), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_column('patients', 'medical_conditions')
    op.drop_column('patients', 'allergies')
    # ### end Alembic commands ###
