"""Initial tables unit fixed

Revision ID: d1cd6f3b83dc
Revises: 
Create Date: 2026-10-09 19:14:20.779345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1cd6f3b83dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'physician', 'admin', name='roleenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admins',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('patients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('biological_sex', sa.String(), nullable=False),
    sa.Column('baseline_height_ft', sa.Double(), nullable=False),
    sa.Column('baseline_weight_lbs', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('physicians',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('medical_license_number', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('medical_license_number')
    )
    op.create_table('patient_physicians',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('physician_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='accessstatusenum'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id', 'physician_id')
    )
    op.create_table('physician_clinics',
    sa.Column('physician_id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['physician_id'], ['physicians.user_id'], ),
    sa.PrimaryKeyConstraint('physician_id', 'clinic_id')
    )
    op.create_table('raw_biomarker_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('biomarker_abbr', sa.String(), nullable=False),
    sa.Column('value', sa.Double(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('measurement_method', sa.String(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_biomarker_logs_patient_id'), 'raw_biomarker_logs', ['patient_id'], unique=False)
    op.create_table('twins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('t_zero_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twins')
    op.drop_index(op.f('ix_raw_biomarker_logs_patient_id'), table_name='raw_biomarker_logs')
    op.drop_table('raw_biomarker_logs')
    op.drop_table('physician_clinics')
    op.drop_table('patient_physicians')
    op.drop_table('physicians')
    op.drop_table('patients')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('clinics')
    # ### end Alembic commands ###
