import uuid
from datetime import datetime
from typing import Any, Dict
from sqlalchemy import String, ForeignKey, DateTime, func
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.users import Patient

class RawBiomarkerLog(Base):
    """Longitudinal time-series data ingested from wearables and lab uploads."""
    __tablename__ = "raw_biomarker_logs"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    patient_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("patients.user_id"), index=True)
    biomarker_abbr: Mapped[str] = mapped_column(String)
    value: Mapped[float] = mapped_column()
    unit: Mapped[str] = mapped_column(String)
    measurement_method: Mapped[str] = mapped_column(String)
    measured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    patient: Mapped["Patient"] = relationship(back_populates="biomarker_logs")


class Twin(Base):
    """The computed $t=0$ digital twin state generated by the Celery simulation engine."""
    __tablename__ = "twins"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    patient_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("patients.user_id"), unique=True)
    
    # JSONB is crucial here to store nested Bayesian distributions and confidence intervals
    t_zero_state: Mapped[Dict[str, Any]] = mapped_column(JSONB)
    
    last_updated: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    patient: Mapped["Patient"] = relationship(back_populates="twin")